PDC = {
    00: "Unknown",
    51: "Aircraft Emergency",
    52: "Fire Alarm",
    53: "Citizen Assist/Service Call",
    54: "Confined Space/Structure Collapse",
    55: "Electrical Hazard",
    56: "Elevator/Escalator Rescue",
    57: "Explosion",
    58: "Extrication/Entrapped",
    59: "Fuel Spill",
    60: "Gas Leak/Gas Odor",
    61: "HAZMAT",
    62: "High Angle Rescue",
    63: "Lightning Strike",
    64: "Marine Fire",
    65: "Mutual Aid/Assist Outside Agency",
    66: "Odor/Unknown",
    67: "Outside Fire",
    68: "Smoke Investigation - Outside",
    69: "Structure Fire",
    70: "Train and Rail Collision/Derailment",
    71: "Vehicle Fire",
    72: "Water Rescue",
    73: "Watercraft in Distress",
    74: "Suspicious Package",
    75: "Train and Rail Fire"
}